// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	ID         int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`           // 主键
	CreatedAt  time.Time      `gorm:"column:created_at;type:datetime(3);comment:记录创建时间" json:"created_at"`                             // 记录创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:datetime(3);comment:记录更新时间" json:"updated_at"`                             // 记录更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);comment:软删除时间" json:"deleted_at"`                              // 软删除时间
	UserID     int64          `gorm:"column:user_id;type:bigint(20) unsigned;comment:发布评论的用户id" json:"user_id"`                        // 发布评论的用户id
	VideoID    int64          `gorm:"column:video_id;type:bigint(20) unsigned;comment:评论视频的id" json:"video_id"`                        // 评论视频的id
	Content    string         `gorm:"column:content;type:varchar(191);not null;comment:评论的内容" json:"content"`                          // 评论的内容
	ActionType  int64        `gorm:"column:action_type;type:enum('1','2');not null;comment:评论行为，1表示已发布评论，2表示删除评论" json:"action_type"` // 评论行为，1表示已发布评论，2表示删除评论
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
