// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID         int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`      // 主键
	CreatedAt  time.Time      `gorm:"column:created_at;type:datetime(3);comment:记录创建时间" json:"created_at"`                        // 记录创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:datetime(3);comment:记录更新时间" json:"updated_at"`                        // 记录更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);comment:软删除时间" json:"deleted_at"`                         // 软删除时间
	SenderID   int64          `gorm:"column:sender_id;type:bigint(20) unsigned;comment:发送message的user id" json:"sender_id"`       // 发送message的user id
	ReceiverID int64          `gorm:"column:receiver_id;type:bigint(20) unsigned;comment:接收message的user id" json:"receiver_id"`   // 接收message的user id
	Content    string         `gorm:"column:content;type:varchar(191);not null;comment:消息内容" json:"content"`                      // 消息内容
	ActionType string         `gorm:"column:action_type;type:enum('1','2');not null;comment:消息行为，1表示发送/2表示撤回" json:"action_type"` // 消息行为，1表示发送/2表示撤回
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
