// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID              int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                                      // 主键
	CreatedAt       time.Time      `gorm:"column:created_at;type:datetime(3);comment:记录创建时间" json:"created_at"`                                                                        // 记录创建时间
	UpdatedAt       time.Time      `gorm:"column:updated_at;type:datetime(3);comment:记录更新时间" json:"updated_at"`                                                                        // 记录更新时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);comment:软删除时间" json:"deleted_at"`                                                                         // 软删除时间
	Name            string         `gorm:"column:name;type:varchar(191);not null;comment:用户名" json:"name"`                                                                             // 用户名
	Password        string         `gorm:"column:password;type:varchar(191);not null;comment:用户密码" json:"password"`                                                                    // 用户密码
	Role            string         `gorm:"column:role;type:varchar(191);not null;comment:角色" json:"role"`                                                                              // 角色
	Avatar          string         `gorm:"column:avatar;type:varchar(191);default:http://yourserver.com/default_avatar.jpg;comment:用户头像链接" json:"avatar"`                              // 用户头像链接
	BackgroundImage string         `gorm:"column:background_image;type:varchar(191);default:http://yourserver.com/default_background.jpg;comment:用户个人页顶部大图链接" json:"background_image"` // 用户个人页顶部大图链接
	Signature       string         `gorm:"column:signature;type:text;comment:个人简介" json:"signature"`                                                                                   // 个人简介
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
